### ISSUE TITLE
Only return Fail...

### ISSUE THREAD

**Issue by ncamilo** [RobTillaart/I2CKeyPad#2]
I made this project and connections but, colun one is ok and another just returns Fail, my keyboard is ok and only Fail on colls 2, 3 and 4, thanks in advance

**Comment by RobTillaart** [comment]
@ncamilo 
Apologies for the (very) late response - being too busy with other things -.

Is this issue still a problem? Or did you manage to get it working?

**Comment by RobTillaart** [comment]
If problem persists please please reopen issue
